//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.02 at 04:41:54 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.kchaou.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kchaou.webservices;
